### ISSUE TITLE
Unable to import the database

### ISSUE THREAD

**Issue by undercutspiky** [ilmaro8/Data_Driven_Color_Augmentation#1]
Hi,
I downloaded the database file `database_color_variations.pickle` and I'm trying to import it as follows (just like in the script provided

https://github.com/ilmaro8/Data_Driven_Color_Augmentation/blob/31bd55ff4c6f0f8963b5a17542729d9f63fc1da3/scripts/Training_new_augmentation.py#L95-L96

```
with open('database_color_variations.pickle', 'rb') as f:
    kdt = pickle.load(f)
```

but I get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "ckdtree.pyx", line 1531, in scipy.spatial.ckdtree.cKDTree.__setstate__
TypeError: expected bytes, numpy.ndarray found
```

**Comment by undercutspiky** [comment]
It seems like it was a version issue. The issue got resolved once I upgraded my scipy.
